### ISSUE TITLE
Tabix issue

### ISSUE THREAD

**Issue by jpbakewell** [HurlesGroupSanger/indelible#1]
Tabix failing to index some bg.gz files

Error:

`Traceback (most recent call last):
  File "/usr/src/app/Indelible/indelible.py", line 127, in <module>
    indelible.aggregate_positions(args.input_path, args.input_bam, args.output_path, args.reference_path, config)
  File "/usr/src/app/Indelible/indelible/aggregate_positions.py", line 151, in aggregate_positions
    cov_calc = CoverageCalculator(chr_dict, input_bam, input_path, config)
  File "/usr/src/app/Indelible/indelible/coverage_calculator.py", line 37, in __init__
    self.__decide_coverage_method()
  File "/usr/src/app/Indelible/indelible/coverage_calculator.py", line 61, in __decide_coverage_method
    self.__calculate_coverage_bam(output_file)
  File "/usr/src/app/Indelible/indelible/coverage_calculator.py", line 70, in __calculate_coverage_bam
    bgzip_and_tabix(output_file)
  File "/usr/src/app/Indelible/indelible/indelible_lib.py", line 75, in bgzip_and_tabix
    raise Exception("tabix on the file " + path + ".gz did not run properly... Exiting!")
Exception: tabix on the file /scratch/c.c1860517/reprocessed_bams/indelible_output_1/JW28032.RG.sc_reads.bg.gz did not run properly... Exiting!
`

**Comment by eugenegardner** [comment]
Hi @jpbakewell,

Could you try pulling checking out the test branch (referenced in #2) and giving InDelible a test to see if it works? I have done tests on my end, but want to be sure before I merge with main.

Should be able to do something like:

```
git clone https://github.com/HurlesGroupSanger/indelible.git
cd indelible
git checkout bedtoolsfix
```

~ Eugene
